### ISSUE TITLE
i will love to do copywriting for you 

### ISSUE THREAD

**Issue by Hamzeto938** [jayrambhia/MovieRatings#38]
I love your application and would want to contribute to it, I'm not a developer but I am good at copywriting. I would love to make a copywrite for your Readme and make a pull request for you to merge. Your response would be highly appreciated. Also I would like to request if we could communicate via email, so I don't have to create issues. Thank you.

**Comment by jayrambhia** [comment]
Hi @Hamzeto938 That would be great. And I really appreciate it. You can find my email id on my profile page. Feel free to email me or at `flutter.rating [at] gmail`.
